source 'https://rubygems.org'

gem 'bootstrap-sass', '~> 3.3.4'
gem 'coffee-rails', '~> 4.0.0'
gem 'haml-rails'
gem 'humanize'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'rails', '4.1.7'
gem 'redcarpet'
gem 'sass-rails', '~> 4.0.3'
gem 'sqlite3'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'

gem 'sdoc', '~> 0.4.0', group: :doc

group :development do
  gem 'pry-nav', group: :test
  gem 'pry-rails', group: :test
  gem 'rspec-rails', group: :test
  gem 'spring'
end

group :test do
  gem 'capybara'
end
